### PR TITLE
Change to customary port number

### PR DESCRIPTION
**Pull request by ngsw**

### CODE REVIEW

**Comment by williebsweet** [comment]
Hey @ngsw, we chose 5432 since it's the [default port](https://www.postgresql.org/docs/current/app-postgres.html).

**Comment by kylemcnair** [comment]
> Hey @ngsw, we chose 5432 since it's the [default port](https://www.postgresql.org/docs/current/app-postgres.html).
> 
> Unless we missed something, I'll go ahead and close this PR.

Seems like 3306 is the default port for mysql
https://dev.mysql.com/doc/mysql-port-reference/en/mysql-ports-reference-tables.html#:~:text=Port%203306%20is%20the%20default,such%20as%20mysqldump%20and%20mysqlpump.

**Comment by williebsweet** [comment]
> > Hey @ngsw, we chose 5432 since it's the [default port](https://www.postgresql.org/docs/current/app-postgres.html).
> > Unless we missed something, I'll go ahead and close this PR.
> 
> Seems like 3306 is the default port for mysql https://dev.mysql.com/doc/mysql-port-reference/en/mysql-ports-reference-tables.html#:~:text=Port%203306%20is%20the%20default,such%20as%20mysqldump%20and%20mysqlpump.

Good catch - I was looking at PostgreSQL.

**Review by williebsweet — APPROVED** [review]

**Comment by williebsweet** [comment]
@ngsw Thanks for your contribution!

**Pull request merged**
