### PR TITLE
Kristal px 162 update onprem section docs

### PR DESCRIPTION
**Pull request by KGmajor**
I have to gather some notes on the GCP on-prem install, but the other sections are complete.

### CODE REVIEW

**Review by dlawin — APPROVED** [review]
Looks great, nothing jumped out at me to change

**Comment by leoebfolsom** [comment]
made some copy edits, looks good!

**Comment by kylemcnair** [comment]
Would it make sense to put the info disclaimer on the overview page too? The subtitles on the cards are duplicative and letting users know at the top might be nice
Screen Shot 2022-10-17 at 1 28 26 PM

```
:::info

On-prem deployments are an Enterprise feature. Please email [sales@datafold.com](mailto:sales@datafold.com) to enable your account. 

:::
```

**Review by kylemcnair — APPROVED** [review]
looks great to me! I mostly read through for grammar etc, nothing jumped out 🚀

**Pull request merged**
