### PR TITLE
Splitting CI config docs to be used in the app

### PR DESCRIPTION
**Pull request by sklinov**
- I've split the docs related to CI cofig to be used as a single source of truth in the app and docs website itself.
- Also added a few lines from [pypi.org/](https://pypi.org/project/datafold-sdk/) about `datafold-sdk` but feel free to elaborate on that.

### CODE REVIEW

**Review by MostFrumiousBandersnatch — APPROVED** [review]

**Comment by MostFrumiousBandersnatch** [comment]
@sklinov Great job, thanks!

**Comment by leoebfolsom** [comment]
Hi @sklinov ! Kyle and I reviewed and like the new organization. Since it's a little hard to tell from the diff since stuff was moved around, would you please call out any content changes that you made, other than restructuring the sections?

**Comment by sklinov** [comment]
@leoebfolsom Major changes here were 
- Copying some `datafold-sdk` docs to `prerequisites.md` and `usage.md` from `pypi.org`
- Copying `trigger.md` section for `dbt-cloud` from previous version of the docs (before major migration).

**Review by leoebfolsom — APPROVED** [review]
I have some minor wording edits that I would like to implement, and sections I would like to expand on, but they are not crucial, and so I think it's better to merge this as-is so that these substantial updates are not blocked by non-critical changes, and then do refinements as part of a separate PR. Thank you @sklinov !

**Pull request merged**
