### PR TITLE
instruct onprem customers to set DATAFOLD_HOST var

### PR DESCRIPTION
**Pull request by leoebfolsom**
With the release of 0.6.0, customers that use a custom host can use `--cloud`, but they need to set a DATAFOLD_HOST var.

### CODE REVIEW

**Comment by leoebfolsom** [comment]
@dlawin having a bit of trouble with npm/docusaurus so I haven't run this locally, but hopefully this change is trivial and reaosnable? lmk, happy to iterate. Also I'll confirm once I've gotten it to run locally.

**Comment by leoebfolsom** [comment]
got it to run locally, ready for review

**Review by williebsweet — APPROVED** [review]
Can winning propose a similar fix in #143

**Comment by leoebfolsom** [comment]
I assume by "Can winning propose" you mean "Can you please propose"

if so, I already did! https://github.com/datafold/datafold-docs/pull/143#discussion_r1156511501

Thanks for shipping this.

**Comment by williebsweet** [comment]
> @williebsweet I assume by "Can winning propose" you mean "Can you please propose"
> 
> if so, I already did! [#143 (comment)](https://github.com/datafold/datafold-docs/pull/143#discussion_r1156511501)
> 
> Thanks for shipping this.

Thanks @leoebfolsom! I’m glad you can read bad autocorrects.

**Pull request merged**
